server:
  port: 8889

spring:
  zipkin:
    enabled: true
    base-url: http://10.108.5.38:9411
    service:
      name: git-config-server
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HR-Management-System-Organization/BE-HR-Management-System.git
          default-label: master
          skip-ssl-validation: true
          username: ${java10-git-username}
          password: ${java10-git-password}
