server:
  port: 7075
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${java9mail}
    password: ${java9mailpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  mail-queue: mailQueue


logging:
  level:
    root: info
  file:
    name: elastic.log
  logback:
    rollingpolicy:
      max-file-size: 100MB